owner: kubernetes
repo: kops
assets:
  - source: darwin/amd64/kops
    githubName: kops-darwin-amd64
  - source: darwin/amd64/kops.sha256
    githubName: kops-darwin-amd64.sha256
  - source: linux/amd64/kops
    githubName: kops-linux-amd64
  - source: linux/amd64/kops.sha256
    githubName: kops-linux-amd64.sha256
  - source: linux/arm64/kops
    githubName: kops-linux-arm64
  - source: linux/arm64/kops.sha256
    githubName: kops-linux-arm64.sha256
  - source: windows/amd64/kops.exe
    githubName: kops-windows-amd64
  - source: windows/amd64/kops.exe.sha256
    githubName: kops-windows-amd64.sha256
  - source: images/protokube-amd64.tar.gz
    githubName: images-protokube-amd64.tar.gz
  - source: images/protokube-arm64.tar.gz
    githubName: images-protokube-arm64.tar.gz
  - source: images/protokube.tar.gz.sha256
    githubName: images-protokube.tar.gz.sha256
  - source: linux/amd64/nodeup
    githubName: linux-amd64-nodeup
  - source: linux/amd64/nodeup.sha256
    githubName: linux-amd64-nodeup.sha256
  - source: linux/arm64/nodeup
    githubName: linux-arm64-nodeup
  - source: linux/arm64/nodeup.sha256
    githubName: linux-arm64-nodeup.sha256
