sudo: required
language: go
go:
  - 1.8
  - 1.9
# removed because of govet issue with apimahcinery
#  - tip

cache:
  directories:
    - $HOME/bazel/outbase

go_import_path: k8s.io/kops

before_install:
- echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
- curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
- sudo apt-get -y update
- sudo apt-get -y install bazel

script:
  # TODO uncomment this
  # - make ci
  # TODO make an option to pass in outbase?
  - bazel --output_base=${HOME}/bazel/outbase test //cmd/... //pkg/... //channels/... //nodeup/... //channels/... //protokube/... //dns-controller/... --test_output=errors
 
git:
  submodules: false
