language: go
arch:
  - amd64
  - arm64
os:
  - linux
  - osx
go:
  # 1.12 is no longer supported by apimachinery; we recommend 1.13
  - "1.13"
  - "1.14"

go_import_path: k8s.io/kops

script:
  - GOPROXY=https://proxy.golang.org travis_wait 20 make nodeup examples test

jobs:
  # Exclude GO 1.14 for OSX until it becomes the default because of limited availability
  exclude:
    - os: osx
      go: "1.14"

  include:
    - name: Verify
      arch: amd64
      os: linux
      go: "1.13"
      script:
        - GOPROXY=https://proxy.golang.org make travis-ci
