language: go
arch:
  - amd64
  - arm64
os:
  - linux
  - osx
dist: focal
go: 1.14.x

go_import_path: k8s.io/kops

script:
  - GOPROXY=https://proxy.golang.org travis_wait 30 make all examples test

jobs:
  include:
    - name: Verify
      arch: amd64
      os: linux
      dist: focal
      go: 1.14.x
      script:
        - GOPROXY=https://proxy.golang.org make travis-ci
