language: go
os:
  - linux
  - osx
go:
  - 1.8
  - 1.9
  - "1.10"
# removed because of govet issue with apimahcinery
#  - tip

go_import_path: k8s.io/kops

script:
  - make ci
  - hack/verify-apimachinery.sh
