language: go
os:
  - linux
  - osx
go:
  # 1.12 is no longer supported by apimachinery; we recommend 1.13
  - "1.13"
  - "1.14"

go_import_path: k8s.io/kops

script:
  - GOPROXY=https://proxy.golang.org make nodeup examples test

jobs:
  # To exclude a known-bad configuration:
  #exclude:
  #  - os: osx
  #    go: "1.12"

  include:
    - name: Verify
      os: linux
      go: "1.13"
      script:
        - GOPROXY=https://proxy.golang.org make travis-ci
