language: go
os:
  - linux
  - osx
go:
  # 1.11 & 1.12 are now best-effort; we recommend 1.13
  - "1.11"
  - "1.12"
  - "1.13"

go_import_path: k8s.io/kops

script:
  - GOPROXY=https://proxy.golang.org make travis-ci
