site_name: Kubernetes Operations - kops
# strict: true
repo_name: 'kubernetes/kops'
repo_url: 'https://github.com/kubernetes/kops'
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: true
theme:
  name: material
  feature:
    tabs: true
  logo:
    icon: 'public'   # globe icon
  palette:
    primary: 'teal'
    accent: 'green'
plugins:
  - search

extra_css: [extra.css]

nav:
  - Welcome:
    - Welcome: "index.md"
    - Releases & Versioning: "welcome/releases.md"
    - Contributing: "welcome/contributing.md"
    - Office Hours: "welcome/office_hours.md"
  - Getting Started:
    - Installing: "getting_started/install.md"
    - Deploying to AWS: "getting_started/aws.md"
    - Deploying to GCE: "getting_started/gce.md"
    - Deploying to OpenStack - Beta: "getting_started/openstack.md"
    - Deploying to Digital Ocean - Alpha: "getting_started/digitalocean.md"
    - kubectl usage: "kubectl.md"
  - CLI:
    - kops: "cli/kops.md"
    - kops completion: "cli/kops_completion.md"
    - kops create: "cli/kops_create.md"
    - kops delete: "cli/kops_delete.md"
    - kops describe: "cli/kops_describe.md"
    - kops edit: "cli/kops_edit.md"
    - kops export: "cli/kops_export.md"
    - kops get: "cli/kops_get.md"
    - kops import: "cli/kops_import.md"
    - kops replace: "cli/kops_replace.md"
    - kops rolling-update: "cli/kops_rolling-update.md"
    - kops set: "cli/kops_set.md"
    - kops toolbox: "cli/kops_toolbox.md"
    - kops update: "cli/kops_update.md"
    - kops upgrade: "cli/kops_upgrade.md"
    - kops validate: "cli/kops_validate.md"
    - kops version: "cli/kops_version.md"
  - API:
    - Cluster Spec: "cluster_spec.md"
    - Instance Group API: "instance_groups.md"
    - Using Manifests and Customizing: "manifests_and_customizing_via_api.md"
    - Godocs for Cluster - ClusterSpec: "https://godoc.org/k8s.io/kops/pkg/apis/kops#ClusterSpec"
    - Godocs for Instance Group - InstanceGroupSpec: "https://godoc.org/k8s.io/kops/pkg/apis/kops#InstanceGroupSpec"

  - Usage:
    - Commands: "usage/commands.md"
    - Arguments: "usage/arguments.md"
  - Operations:
    - Cluster Addons & Manager : "operations/addons.md"
    - Cluster configuration management: "changing_configuration.md"
    - Cluster Templating: "operations/cluster_template.md"
    - Cluster upgrades and migrations: "operations/cluster_upgrades_and_migrations.md"
    - etcd volume encryption setup: "etcd_volume_encryption.md"
    - etcd backup/restore: "etcd/backup-restore.md"
    - GPU setup: "gpu.md"
    - High Availability: "high_availability.md"
    - InstanceGroup images: "images.md"
    - k8s upgrading: "upgrade.md"
    - kops updating: "update_kops.md"
    - kube-up to kops upgrade: "upgrade_from_kubeup.md"
    - Label management: "labels.md"
    - Secret management: "secrets.md"
    - Moving from a Single Master to Multiple HA Masters: "single-to-multi-master.md"
    - Upgrading Kubernetes: "tutorial/upgrading-kubernetes.md"
    - Working with Instance Groups: "tutorial/working-with-instancegroups.md"
    - Developers guide for vSphere support: "vsphere-dev.md"
    - vSphere support status: "vsphere-development-status.md"
    - Running kops in a CI environment: "continuous_integration.md"
  - Networking:
    - Networking Overview including CNI: "networking.md"
    - Run kops in an existing VPC: "run_in_existing_vpc.md"
    - Supported network topologies: "topology.md"
    - Subdomain setup: "creating_subdomain.md"
  - Security:
    - Security: "security.md"
    - Bastion setup: "bastion.md"
    - IAM roles: "iam_roles.md"
    - MFA setup: "mfa.md"
  - Advanced:
    - Download Config: "advanced/download_config.md"
    - Subdomain NS Records: "advanced/ns.md"
    - Experimental: "advanced/experimental.md"
    - Cluster boot sequence: "boot-sequence.md"
    - Philosophy: "philosophy.md"
    - State store: "state.md"
  - Development:
    - Developing using Docker: "development/Docker.md"
    - Development with vSphere: "vsphere-dev.md"
    - Documentation Guidelines: "development/documentation.md"
    - E2E testing with `kops` clusters: "development/testing.md"
    - Example on how to add a feature: "development/adding_a_feature.md"
    - Hack Directory: "development/hack.md"
    - How to update `kops` API: "development/api_updates.md"
    - Low level description on how kops works: "development/how_it_works.md"
    - Notes on Gossip design: "development/gossip.md"
    - Notes on master instance sizing: "development/instancesizes.md"
    - Our release process: "development/release.md"
    - Releasing with Homebrew: "development/homebrew.md"
    - Rolling Update Diagrams: "development/rolling_update.md"
