apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kopeio-networking-agent
  namespace: kube-system
  labels:
    k8s-addon: networking.addons.k8s.io
spec:
  template:
    metadata:
      labels:
        name: kopeio-networking-agent
    spec:
      hostPID: true
      hostIPC: true
      hostNetwork: true
      containers:
        - resources:
            requests:
              cpu: 0.20
          securityContext:
            privileged: true
          image: kopeio/networking-agent:1.0.20161116
          name: networking-agent
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
