timeout: 3600s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '-t', 'gcr.io/$PROJECT_ID/jupyter-base:latest',
          '-f', 'Dockerfile',
          '.'
        ]
images:
- gcr.io/$PROJECT_ID/jupyter-base:latest
