---
name: CI

'on':
  - pull_request

env:
  GOPROXY: https://proxy.golang.org
  GOPATH: ${{ github.workspace }}/go

jobs:
  build-linux-arm64:
    runs-on: linux-arm64
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.2

      - uses: actions/checkout@v2
        with:
          path: ${{ env.GOPATH }}/src/k8s.io/kops

      - name: make all examples test
        working-directory: ${{ env.GOPATH }}/src/k8s.io/kops
        run: |
          make all examples test
