name: 'Review Dependencies'

on:
  pull_request:
    paths:
      - 'go.mod'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Review Dependencies'
        uses: actions/dependency-review-action@v2
