name: 'Review Dependencies'

on:
  pull_request:
    paths:
      - 'go.mod'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: 'Review Dependencies'
        uses: actions/dependency-review-action@94145f3150bfabdc97540cbd5f7e926306ea7744
